//! Loams integration for the desktop fork of zeron.
//!
//! Everything Loams-specific that is not branding lives in this crate, so the
//! fork's diff against upstream stays small and rebases stay cheap
//! (`LOAMS.md`). It has no GPUI dependency: it builds and tests in a fraction
//! of the time of the UI crates.
//!
//! - [`client`] and [`mock`]: Connect-RPC to a local `loams` server, and an
//!   in-process mock of it (`LOAMS_MOCK=1`).
//! - [`auth`]: Authentik OIDC sign-in (PKCE, system browser, OS keychain).
//! - [`a2a`]: the stub A2A client Loams Bot delegates with.
//! - [`acp`]: Loams Bot as an ACP agent, which is how zeron's engine and chat
//!   UI drive it.
//! - [`cli`]: the `zeron loams …` subcommands that tie these together.

pub mod a2a;
pub mod acp;
/// Identity strings (re-exported so callers need one import).
pub use loams_brand as brand;
pub mod auth;
pub mod cli;
pub mod client;
pub mod config;
pub mod mock;

/// Generated by `buf generate` (see `buf.gen.yaml`): message types.
#[rustfmt::skip]
#[path = "gen/buffa/mod.rs"]
#[allow(missing_docs, missing_debug_implementations, unreachable_pub, clippy::all, clippy::pedantic)]
pub mod proto;

/// Generated by `buf generate`: connect-rust service stubs and clients.
#[rustfmt::skip]
#[path = "gen/connect/mod.rs"]
#[allow(missing_docs, missing_debug_implementations, unreachable_pub, clippy::all, clippy::pedantic)]
pub mod connect;
